name: "Go"
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Setup"
        uses: "actions/setup-go@v3"
        with:
          go-version: "^1.23"
      - name: "Build"
        run: "go build -v ./..."
      - name: "Test"
        run: "go test -v ./..."
